spring:
  cassandra:
    port: 9042
    schema-action: CREATE_IF_NOT_EXISTS
    contact-points: cassandra
    local-datacenter: datacenter1
    keyspace-name: booktracker

datadump.location:
  .author: /home/rachid/downloads/test-authors.txt
  .works: /home/rachid/downloads/test-works.txt
